config/routes.rb
Rails.application.routes.draw do
  resources :valleys
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dinosaurs
  
  # get "dinosaurs" => "dinosaurs#index"
  # get "dinosaurs/new" => "dinosaurs#new", as: :new_dinosaur
  # get "dinosaurs/:id/edit" => "dinosaurs#edit", as: :edit_dinosaur
  # post "dinosaurs" => "dinosaurs#create"
  # get "dinosaurs/:id" => "dinosaurs#show", as: :dinosaur
  # patch "dinosaurs/:id" => "dinosaurs#update"
  # delete "dinosaurs/:id" => "dinosaurs#destroy"

  root "valleys#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  validates :age, length: { maximum: 5 }, allow_blank: true
  validates :image_url, length: { maximum: 255 }, allow_blank: true
  belongs_to :valley

  def self.order_by_name
    order(:name)
  end

  def is_baby?
    age < 3
  end
end

app/models/valley.rb
class Valley < ApplicationRecord
  has_many :dinosaurs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController

  def index
    @dinosaurs = Dinosaur.all
  end

  def show
    @dinosaur = Dinosaur.find(params[:id])
  end

  def new
    @dinosaur = Dinosaur.new
  end

  def create
    dino_params = dinosaur_params

    @dinosaur = Dinosaur.new( dino_params )

    if @dinosaur.save
         redirect_to @dinosaur
    else
       render 'new'
    end
  end

  def edit
      @dinosaur = Dinosaur.find(params[:id])
  end

  def update
    @dinosaur = Dinosaur.find( params[:id] )

    dino_params = dinosaur_params

    if @dinosaur.update_attributes( dino_params )
     redirect_to @dinosaur
    else
     render 'edit'
    end
  end

  def destroy
    @dinosaur = Dinosaur.find(params[:id])

    @dinosaur.destroy

    redirect_to dinosaurs_path
  end


  private

  def dinosaur_params
    params.require(:dinosaur).permit(:name, :age, :image_url, :valley_id)
  end
end

app/controllers/valleys_controller.rb
class ValleysController < ApplicationController
  before_action :set_valley, only: [:show, :edit, :update, :destroy]

  # GET /valleys
  # GET /valleys.json
  def index
    @valleys = Valley.all
  end

  # GET /valleys/1
  # GET /valleys/1.json
  def show
    
  end

  # GET /valleys/new
  def new
    @valley = Valley.new
  end

  # GET /valleys/1/edit
  def edit
  end

  # POST /valleys
  # POST /valleys.json
  def create
    @valley = Valley.new(valley_params)

    respond_to do |format|
      if @valley.save
        format.html { redirect_to @valley, notice: 'Valley was successfully created.' }
        format.json { render :show, status: :created, location: @valley }
      else
        format.html { render :new }
        format.json { render json: @valley.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valleys/1
  # PATCH/PUT /valleys/1.json
  def update
    respond_to do |format|
      if @valley.update(valley_params)
        format.html { redirect_to @valley, notice: 'Valley was successfully updated.' }
        format.json { render :show, status: :ok, location: @valley }
      else
        format.html { render :edit }
        format.json { render json: @valley.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valleys/1
  # DELETE /valleys/1.json
  def destroy
    @valley.destroy
    respond_to do |format|
      format.html { redirect_to valleys_url, notice: 'Valley was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valley
      @valley = Valley.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valley_params
      params.require(:valley).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/helpers/valleys_helper.rb
module ValleysHelper
end

app/views/dinosaurs/_form.html.erb
<div class="col-12 form-data-dinosaur">
  <%= form_for @dinosaur do |f| %>

     <ul>
        <% @dinosaur.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
     </ul>

     <fieldset class="input">
       <%= f.label :name %>
       <%= f.text_field :name %>
     </fieldset>

     <fieldset class="input">
       <%= f.label :age %>
       <%= f.number_field :age %>
     </fieldset>

     <fieldset class="input">
       <%= f.label :image_url %>
       <%= f.text_field :image_url %>
      </fieldset>

      <fieldset class="input">
        <%= f.label :valley_id %>
<%= f.collection_select(:valley_id, Valley.all, :id, :name) %>
      </fieldset>
      <fieldset class="input">
        <%= f.submit (@dinosaur.new_record? ? "Create" : "Update") %>
      </fieldset>
   <% end %>
</div>

app/views/dinosaurs/edit.html.erb
<h1 class="page-title">Edit Dinosaur</h1>
<main class="col-10">

  <%= render "form" %>
</main>

app/views/dinosaurs/index.html.erb
<h1 class="page-title">Dinosaurs</h1>
<a href="<%= new_dinosaur_path %>" class="new">New Dinosaur</a>
<main class="col-10">
  <!-- here come the main -->
  <% @dinosaurs.each do |dinosaur| %>
  <article class="col-3 valley">
    <%= image_tag dinosaur.image_url %>
    <h1><%= dinosaur.name %></h1>
    <p class="col-12">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </p>
    <a href="<%=dinosaur_path(dinosaur.id) %>" class="col-12">Learn more</a>
  </article>

  <% end %>
  </main>

  <footer class="col-12">
    <!-- here come the footer -->
    &#169; 2016 Valley of Dinos
  </footer>

app/views/dinosaurs/new.html.erb
<main class="col-10">
  <h1>New Dinosaur</h1>

    <%= form_for @dinosaur do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.number_field :age %>

    <%= f.label :image_url %>
    <%= f.text_field :image_url %>

    <%= f.submit "Create" %>
    <% end %>
</main>

app/views/dinosaurs/show.html.erb
<h1 class="page-title">Dinosaur</h1>

<main class="col-10">
  <article class="col-10 dinos">
    <%= image_tag @dinosaur.image_url %>
    <div class= "col-9 description">
      <h1><%= @dinosaur.name %></h1> <p>Age: <%= @dinosaur.age %></p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <div class="col-12 links">
        <ul>
          <li>Carrion</li>
          <li>Plants</li>
        </ul>
        <div class="options">
          <a href="<%= edit_dinosaur_path( @dinosaur.id ) %>">Edit</a>
          <%= link_to "Delete", dinosaur_path( @dinosaur.id ), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
  </article>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValleysOfDinosaurs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="favicon.png"/>
    <link rel="shortcut icon" type="image/png" href="http://www.valleyofdinosaurs.bitballoon.com/favicon.png"/>
  </head>

  <body>
    <header>
      <!-- here come the header -->
      <a href="<%= root_path %>" class="col-9"><h1>Valley of Dinos</h1></a>
      <nav>
        <ul class="col-3">
          <a href="<%= dinosaurs_path %>"><li>Dinosaurs</li></a>
          <a href="#"><li>About</li></a>
          <a href="#"><li>Contact</li></a>
        </ul>
      </nav>
    </header>
    <div class="col-12 banner">
      <!-- here come the banner-->
      <%= image_tag("dinosaurs_era.jpg", :alt => "Dinosaur Era") %>
      <h1> Discover the Dinosaurs era</h1>
      <h2>Fun facts going in Time</h2>
    </div>
    <%= yield %>
  </body>
</html>

app/views/valleys/_form.html.erb
<%= form_for(valley) do |f| %>
  <% if valley.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valley.errors.count, "error") %> prohibited this valley from being saved:</h2>

      <ul>
      <% valley.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/valleys/edit.html.erb
<h1>Editing Valley</h1>

<%= render 'form', valley: @valley %>

<%= link_to 'Show', @valley %> |
<%= link_to 'Back', valleys_path %>

app/views/valleys/index.html.erb
<h1 class="col-12 page-title">Valley</h1>
<p id="notice"><%= notice %></p>

<main class="col-10">
  <!-- here come the main -->
  <% @valleys.each do |valley| %>
  <article class="col-3 valley">

    <h1><%= valley.name %></h1>
    <p class="col-12">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </p>
    <a href="<%=valley_path(valley.id) %>" class="col-12">Learn more</a>
  </article>

  <% end %>
</main>

  <footer class="col-12">
    <!-- here come the footer -->
    &#169; 2016 Valley of Dinos
  </footer>

app/views/valleys/new.html.erb
<h1>New Valley</h1>

<%= render 'form', valley: @valley %>

<%= link_to 'Back', valleys_path %>

app/views/valleys/show.html.erb
<h1 class="page-title"><%= @valley.name %></h1>
<p id="notice"><%= notice %></p>

<main class="col-10">

  <% if @valley.dinosaurs.any? %>
    <% @valley.dinosaurs.each do |dino| %>
      <article class="col-3 valley">
        <%= image_tag dino.image_url %>
        <h1><%= dino.name %></h1>
        <p class="col-12">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
        <a href="<%=dinosaur_path(dino.id) %>" class="col-12">Learn more</a>
      </article>
    <% end %>
  <% else %>
    <p>There are no dinos in this valley.</p>
  <% end %>